// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: kv/proto/kv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OdsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size          int64           `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`                                                                                                                                //The full expected size of the object upon completion
	LocationInfos map[string]bool `protobuf:"bytes,2,rep,name=location_infos,json=locationInfos,proto3" json:"location_infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //node and completion status pairing (1 if complete, 0 if partial)
}

func (x *OdsInfo) Reset() {
	*x = OdsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsInfo) ProtoMessage() {}

func (x *OdsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsInfo.ProtoReflect.Descriptor instead.
func (*OdsInfo) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *OdsInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OdsInfo) GetLocationInfos() map[string]bool {
	if x != nil {
		return x.LocationInfos
	}
	return nil
}

type OdsGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *OdsGetRequest) Reset() {
	*x = OdsGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsGetRequest) ProtoMessage() {}

func (x *OdsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsGetRequest.ProtoReflect.Descriptor instead.
func (*OdsGetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *OdsGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OdsSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *OdsInfo `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` //LocationInfos should have 1 element in this case
	TtlMs int64    `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
}

func (x *OdsSetRequest) Reset() {
	*x = OdsSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsSetRequest) ProtoMessage() {}

func (x *OdsSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsSetRequest.ProtoReflect.Descriptor instead.
func (*OdsSetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *OdsSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OdsSetRequest) GetValue() *OdsInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OdsSetRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type OdsDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	NodeName string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
}

func (x *OdsDeleteRequest) Reset() {
	*x = OdsDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsDeleteRequest) ProtoMessage() {}

func (x *OdsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsDeleteRequest.ProtoReflect.Descriptor instead.
func (*OdsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *OdsDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OdsDeleteRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type OdsGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    *OdsInfo `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	WasFound bool     `protobuf:"varint,2,opt,name=was_found,json=wasFound,proto3" json:"was_found,omitempty"`
}

func (x *OdsGetResponse) Reset() {
	*x = OdsGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsGetResponse) ProtoMessage() {}

func (x *OdsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsGetResponse.ProtoReflect.Descriptor instead.
func (*OdsGetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *OdsGetResponse) GetValue() *OdsInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OdsGetResponse) GetWasFound() bool {
	if x != nil {
		return x.WasFound
	}
	return false
}

type OdsSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OdsSetResponse) Reset() {
	*x = OdsSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsSetResponse) ProtoMessage() {}

func (x *OdsSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsSetResponse.ProtoReflect.Descriptor instead.
func (*OdsSetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{5}
}

type OdsDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OdsDeleteResponse) Reset() {
	*x = OdsDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsDeleteResponse) ProtoMessage() {}

func (x *OdsDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsDeleteResponse.ProtoReflect.Descriptor instead.
func (*OdsDeleteResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{6}
}

type GetShardContentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard int32 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
}

func (x *GetShardContentsRequest) Reset() {
	*x = GetShardContentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShardContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardContentsRequest) ProtoMessage() {}

func (x *GetShardContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardContentsRequest.ProtoReflect.Descriptor instead.
func (*GetShardContentsRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *GetShardContentsRequest) GetShard() int32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

type GetShardValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *OdsInfo `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetShardValue) Reset() {
	*x = GetShardValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShardValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardValue) ProtoMessage() {}

func (x *GetShardValue) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardValue.ProtoReflect.Descriptor instead.
func (*GetShardValue) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{8}
}

func (x *GetShardValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetShardValue) GetValue() *OdsInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetShardContentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*GetShardValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *GetShardContentsResponse) Reset() {
	*x = GetShardContentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShardContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardContentsResponse) ProtoMessage() {}

func (x *GetShardContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardContentsResponse.ProtoReflect.Descriptor instead.
func (*GetShardContentsResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{9}
}

func (x *GetShardContentsResponse) GetValues() []*GetShardValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId      string            `protobuf:"bytes,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"` //object id of the to-be created object
	TaskId     int32             `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Args       []string          `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`                                                                                                                           //List of arguments as objId’s associated with the task
	ObjIdToObj map[string][]byte `protobuf:"bytes,4,rep,name=obj_id_to_obj,json=objIdToObj,proto3" json:"obj_id_to_obj,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //Pre-specified params (“generic” type)
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{10}
}

func (x *TaskRequest) GetObjId() string {
	if x != nil {
		return x.ObjId
	}
	return ""
}

func (x *TaskRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TaskRequest) GetObjIdToObj() map[string][]byte {
	if x != nil {
		return x.ObjIdToObj
	}
	return nil
}

type TaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{11}
}

type TaskAnsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId string `protobuf:"bytes,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
}

func (x *TaskAnsRequest) Reset() {
	*x = TaskAnsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskAnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAnsRequest) ProtoMessage() {}

func (x *TaskAnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAnsRequest.ProtoReflect.Descriptor instead.
func (*TaskAnsRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{12}
}

func (x *TaskAnsRequest) GetObjId() string {
	if x != nil {
		return x.ObjId
	}
	return ""
}

type TaskAnsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []byte `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *TaskAnsResponse) Reset() {
	*x = TaskAnsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_proto_kv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskAnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAnsResponse) ProtoMessage() {}

func (x *TaskAnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_kv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAnsResponse.ProtoReflect.Descriptor instead.
func (*TaskAnsResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_kv_proto_rawDescGZIP(), []int{13}
}

func (x *TaskAnsResponse) GetRes() []byte {
	if x != nil {
		return x.Res
	}
	return nil
}

var File_kv_proto_kv_proto protoreflect.FileDescriptor

var file_kv_proto_kv_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6b, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x76, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x6b, 0x76, 0x22, 0xa6, 0x01, 0x0a, 0x07, 0x4f, 0x64, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x45, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x1a, 0x40,
	0x0a, 0x12, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x21, 0x0a, 0x0d, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x5b, 0x0a, 0x0d, 0x4f, 0x64, 0x73, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x74, 0x6c,
	0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x74, 0x6c, 0x4d, 0x73,
	0x22, 0x41, 0x0a, 0x10, 0x4f, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x0e, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x73, 0x5f,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x77, 0x61, 0x73,
	0x46, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x4f, 0x64, 0x73, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x4f, 0x64, 0x73, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x22, 0x44, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x45, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x29, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6b, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xd4, 0x01, 0x0a, 0x0b, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x62,
	0x6a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x42,
	0x0a, 0x0d, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x6f, 0x62, 0x6a, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b, 0x76, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x54, 0x6f, 0x4f, 0x62,
	0x6a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x54, 0x6f, 0x4f,
	0x62, 0x6a, 0x1a, 0x3d, 0x0a, 0x0f, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x54, 0x6f, 0x4f, 0x62, 0x6a,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x0e, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x27, 0x0a, 0x0e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x0f, 0x54, 0x61,
	0x73, 0x6b, 0x41, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65, 0x73, 0x32,
	0xef, 0x01, 0x0a, 0x02, 0x4b, 0x76, 0x12, 0x2f, 0x0a, 0x06, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74,
	0x12, 0x11, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x4f, 0x64, 0x73, 0x53, 0x65,
	0x74, 0x12, 0x11, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x4f, 0x64, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x6b, 0x76, 0x2e, 0x4f, 0x64, 0x73, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6b, 0x76,
	0x2e, 0x4f, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x6b, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6b, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x63, 0x73, 0x34, 0x32, 0x36, 0x2e, 0x79, 0x61, 0x6c, 0x65, 0x2e,
	0x65, 0x64, 0x75, 0x2f, 0x6c, 0x61, 0x62, 0x34, 0x2f, 0x6b, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kv_proto_kv_proto_rawDescOnce sync.Once
	file_kv_proto_kv_proto_rawDescData = file_kv_proto_kv_proto_rawDesc
)

func file_kv_proto_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(file_kv_proto_kv_proto_rawDescData)
	})
	return file_kv_proto_kv_proto_rawDescData
}

var file_kv_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_kv_proto_kv_proto_goTypes = []interface{}{
	(*OdsInfo)(nil),                  // 0: kv.OdsInfo
	(*OdsGetRequest)(nil),            // 1: kv.OdsGetRequest
	(*OdsSetRequest)(nil),            // 2: kv.OdsSetRequest
	(*OdsDeleteRequest)(nil),         // 3: kv.OdsDeleteRequest
	(*OdsGetResponse)(nil),           // 4: kv.OdsGetResponse
	(*OdsSetResponse)(nil),           // 5: kv.OdsSetResponse
	(*OdsDeleteResponse)(nil),        // 6: kv.OdsDeleteResponse
	(*GetShardContentsRequest)(nil),  // 7: kv.GetShardContentsRequest
	(*GetShardValue)(nil),            // 8: kv.GetShardValue
	(*GetShardContentsResponse)(nil), // 9: kv.GetShardContentsResponse
	(*TaskRequest)(nil),              // 10: kv.TaskRequest
	(*TaskResponse)(nil),             // 11: kv.TaskResponse
	(*TaskAnsRequest)(nil),           // 12: kv.TaskAnsRequest
	(*TaskAnsResponse)(nil),          // 13: kv.TaskAnsResponse
	nil,                              // 14: kv.OdsInfo.LocationInfosEntry
	nil,                              // 15: kv.TaskRequest.ObjIdToObjEntry
}
var file_kv_proto_kv_proto_depIdxs = []int32{
	14, // 0: kv.OdsInfo.location_infos:type_name -> kv.OdsInfo.LocationInfosEntry
	0,  // 1: kv.OdsSetRequest.value:type_name -> kv.OdsInfo
	0,  // 2: kv.OdsGetResponse.value:type_name -> kv.OdsInfo
	0,  // 3: kv.GetShardValue.value:type_name -> kv.OdsInfo
	8,  // 4: kv.GetShardContentsResponse.values:type_name -> kv.GetShardValue
	15, // 5: kv.TaskRequest.obj_id_to_obj:type_name -> kv.TaskRequest.ObjIdToObjEntry
	1,  // 6: kv.Kv.OdsGet:input_type -> kv.OdsGetRequest
	2,  // 7: kv.Kv.OdsSet:input_type -> kv.OdsSetRequest
	3,  // 8: kv.Kv.OdsDelete:input_type -> kv.OdsDeleteRequest
	7,  // 9: kv.Kv.GetShardContents:input_type -> kv.GetShardContentsRequest
	4,  // 10: kv.Kv.OdsGet:output_type -> kv.OdsGetResponse
	5,  // 11: kv.Kv.OdsSet:output_type -> kv.OdsSetResponse
	6,  // 12: kv.Kv.OdsDelete:output_type -> kv.OdsDeleteResponse
	9,  // 13: kv.Kv.GetShardContents:output_type -> kv.GetShardContentsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kv_proto_kv_proto_init() }
func file_kv_proto_kv_proto_init() {
	if File_kv_proto_kv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kv_proto_kv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShardContentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShardValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShardContentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskAnsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_proto_kv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskAnsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kv_proto_kv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_kv_proto_depIdxs,
		MessageInfos:      file_kv_proto_kv_proto_msgTypes,
	}.Build()
	File_kv_proto_kv_proto = out.File
	file_kv_proto_kv_proto_rawDesc = nil
	file_kv_proto_kv_proto_goTypes = nil
	file_kv_proto_kv_proto_depIdxs = nil
}
