// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: kv/proto/kv.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Kv_OdsGet_FullMethodName           = "/kv.Kv/OdsGet"
	Kv_OdsSet_FullMethodName           = "/kv.Kv/OdsSet"
	Kv_OdsDelete_FullMethodName        = "/kv.Kv/OdsDelete"
	Kv_GetShardContents_FullMethodName = "/kv.Kv/GetShardContents"
)

// KvClient is the client API for Kv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvClient interface {
	OdsGet(ctx context.Context, in *OdsGetRequest, opts ...grpc.CallOption) (*OdsGetResponse, error)
	OdsSet(ctx context.Context, in *OdsSetRequest, opts ...grpc.CallOption) (*OdsSetResponse, error)
	OdsDelete(ctx context.Context, in *OdsDeleteRequest, opts ...grpc.CallOption) (*OdsDeleteResponse, error)
	GetShardContents(ctx context.Context, in *GetShardContentsRequest, opts ...grpc.CallOption) (*GetShardContentsResponse, error)
}

type kvClient struct {
	cc grpc.ClientConnInterface
}

func NewKvClient(cc grpc.ClientConnInterface) KvClient {
	return &kvClient{cc}
}

func (c *kvClient) OdsGet(ctx context.Context, in *OdsGetRequest, opts ...grpc.CallOption) (*OdsGetResponse, error) {
	out := new(OdsGetResponse)
	err := c.cc.Invoke(ctx, Kv_OdsGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) OdsSet(ctx context.Context, in *OdsSetRequest, opts ...grpc.CallOption) (*OdsSetResponse, error) {
	out := new(OdsSetResponse)
	err := c.cc.Invoke(ctx, Kv_OdsSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) OdsDelete(ctx context.Context, in *OdsDeleteRequest, opts ...grpc.CallOption) (*OdsDeleteResponse, error) {
	out := new(OdsDeleteResponse)
	err := c.cc.Invoke(ctx, Kv_OdsDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) GetShardContents(ctx context.Context, in *GetShardContentsRequest, opts ...grpc.CallOption) (*GetShardContentsResponse, error) {
	out := new(GetShardContentsResponse)
	err := c.cc.Invoke(ctx, Kv_GetShardContents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvServer is the server API for Kv service.
// All implementations must embed UnimplementedKvServer
// for forward compatibility
type KvServer interface {
	OdsGet(context.Context, *OdsGetRequest) (*OdsGetResponse, error)
	OdsSet(context.Context, *OdsSetRequest) (*OdsSetResponse, error)
	OdsDelete(context.Context, *OdsDeleteRequest) (*OdsDeleteResponse, error)
	GetShardContents(context.Context, *GetShardContentsRequest) (*GetShardContentsResponse, error)
	mustEmbedUnimplementedKvServer()
}

// UnimplementedKvServer must be embedded to have forward compatible implementations.
type UnimplementedKvServer struct {
}

func (UnimplementedKvServer) OdsGet(context.Context, *OdsGetRequest) (*OdsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OdsGet not implemented")
}
func (UnimplementedKvServer) OdsSet(context.Context, *OdsSetRequest) (*OdsSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OdsSet not implemented")
}
func (UnimplementedKvServer) OdsDelete(context.Context, *OdsDeleteRequest) (*OdsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OdsDelete not implemented")
}
func (UnimplementedKvServer) GetShardContents(context.Context, *GetShardContentsRequest) (*GetShardContentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShardContents not implemented")
}
func (UnimplementedKvServer) mustEmbedUnimplementedKvServer() {}

// UnsafeKvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvServer will
// result in compilation errors.
type UnsafeKvServer interface {
	mustEmbedUnimplementedKvServer()
}

func RegisterKvServer(s grpc.ServiceRegistrar, srv KvServer) {
	s.RegisterService(&Kv_ServiceDesc, srv)
}

func _Kv_OdsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OdsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).OdsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_OdsGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).OdsGet(ctx, req.(*OdsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_OdsSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OdsSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).OdsSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_OdsSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).OdsSet(ctx, req.(*OdsSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_OdsDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OdsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).OdsDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_OdsDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).OdsDelete(ctx, req.(*OdsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_GetShardContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).GetShardContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_GetShardContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).GetShardContents(ctx, req.(*GetShardContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kv_ServiceDesc is the grpc.ServiceDesc for Kv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kv.Kv",
	HandlerType: (*KvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OdsGet",
			Handler:    _Kv_OdsGet_Handler,
		},
		{
			MethodName: "OdsSet",
			Handler:    _Kv_OdsSet_Handler,
		},
		{
			MethodName: "OdsDelete",
			Handler:    _Kv_OdsDelete_Handler,
		},
		{
			MethodName: "GetShardContents",
			Handler:    _Kv_GetShardContents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv/proto/kv.proto",
}
