// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: hoplite.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId      string            `protobuf:"bytes,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"` //object id of the to-be created object
	TaskId     int32             `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Args       []string          `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`                                                                                                                           //List of arguments as objId’s associated with the task
	ObjIdToObj map[string][]byte `protobuf:"bytes,4,rep,name=obj_id_to_obj,json=objIdToObj,proto3" json:"obj_id_to_obj,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //Pre-specified params (“generic” type)
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetObjId() string {
	if x != nil {
		return x.ObjId
	}
	return ""
}

func (x *TaskRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TaskRequest) GetObjIdToObj() map[string][]byte {
	if x != nil {
		return x.ObjIdToObj
	}
	return nil
}

type TaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{1}
}

type TaskAnsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId string `protobuf:"bytes,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
}

func (x *TaskAnsRequest) Reset() {
	*x = TaskAnsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskAnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAnsRequest) ProtoMessage() {}

func (x *TaskAnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAnsRequest.ProtoReflect.Descriptor instead.
func (*TaskAnsRequest) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{2}
}

func (x *TaskAnsRequest) GetObjId() string {
	if x != nil {
		return x.ObjId
	}
	return ""
}

type TaskAnsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []byte `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *TaskAnsResponse) Reset() {
	*x = TaskAnsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskAnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAnsResponse) ProtoMessage() {}

func (x *TaskAnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAnsResponse.ProtoReflect.Descriptor instead.
func (*TaskAnsResponse) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{3}
}

func (x *TaskAnsResponse) GetRes() []byte {
	if x != nil {
		return x.Res
	}
	return nil
}

type OdsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size          int64           `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`                                                                                                                                //The full expected size of the object upon completion
	LocationInfos map[string]bool `protobuf:"bytes,2,rep,name=location_infos,json=locationInfos,proto3" json:"location_infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //node and completion status pairing (1 if complete, 0 if partial)
}

func (x *OdsInfo) Reset() {
	*x = OdsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsInfo) ProtoMessage() {}

func (x *OdsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsInfo.ProtoReflect.Descriptor instead.
func (*OdsInfo) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{4}
}

func (x *OdsInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OdsInfo) GetLocationInfos() map[string]bool {
	if x != nil {
		return x.LocationInfos
	}
	return nil
}

type OdsGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` //object id
}

func (x *OdsGetRequest) Reset() {
	*x = OdsGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsGetRequest) ProtoMessage() {}

func (x *OdsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsGetRequest.ProtoReflect.Descriptor instead.
func (*OdsGetRequest) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{5}
}

func (x *OdsGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OdsGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    *OdsInfo `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	WasFound bool     `protobuf:"varint,2,opt,name=was_found,json=wasFound,proto3" json:"was_found,omitempty"`
}

func (x *OdsGetResponse) Reset() {
	*x = OdsGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsGetResponse) ProtoMessage() {}

func (x *OdsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsGetResponse.ProtoReflect.Descriptor instead.
func (*OdsGetResponse) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{6}
}

func (x *OdsGetResponse) GetValue() *OdsInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OdsGetResponse) GetWasFound() bool {
	if x != nil {
		return x.WasFound
	}
	return false
}

type OdsSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *OdsInfo `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` //LocationInfos should have 1 element in this case
	TtlMs int64    `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
}

func (x *OdsSetRequest) Reset() {
	*x = OdsSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsSetRequest) ProtoMessage() {}

func (x *OdsSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsSetRequest.ProtoReflect.Descriptor instead.
func (*OdsSetRequest) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{7}
}

func (x *OdsSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OdsSetRequest) GetValue() *OdsInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OdsSetRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type OdsSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OdsSetResponse) Reset() {
	*x = OdsSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsSetResponse) ProtoMessage() {}

func (x *OdsSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsSetResponse.ProtoReflect.Descriptor instead.
func (*OdsSetResponse) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{8}
}

type OdsDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	NodeName string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
}

func (x *OdsDeleteRequest) Reset() {
	*x = OdsDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsDeleteRequest) ProtoMessage() {}

func (x *OdsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsDeleteRequest.ProtoReflect.Descriptor instead.
func (*OdsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{9}
}

func (x *OdsDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OdsDeleteRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type OdsDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OdsDeleteResponse) Reset() {
	*x = OdsDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OdsDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdsDeleteResponse) ProtoMessage() {}

func (x *OdsDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdsDeleteResponse.ProtoReflect.Descriptor instead.
func (*OdsDeleteResponse) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{10}
}

type BroadcastObjRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Start    int32  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"` //where to start copying from (to allow for partial copy transmission)
}

func (x *BroadcastObjRequest) Reset() {
	*x = BroadcastObjRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastObjRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastObjRequest) ProtoMessage() {}

func (x *BroadcastObjRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastObjRequest.ProtoReflect.Descriptor instead.
func (*BroadcastObjRequest) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{11}
}

func (x *BroadcastObjRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *BroadcastObjRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

type BroadcastObjResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object []byte `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *BroadcastObjResponse) Reset() {
	*x = BroadcastObjResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastObjResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastObjResponse) ProtoMessage() {}

func (x *BroadcastObjResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastObjResponse.ProtoReflect.Descriptor instead.
func (*BroadcastObjResponse) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{12}
}

func (x *BroadcastObjResponse) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

type DeleteObjRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
}

func (x *DeleteObjRequest) Reset() {
	*x = DeleteObjRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteObjRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjRequest) ProtoMessage() {}

func (x *DeleteObjRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjRequest) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteObjRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type DeleteObjResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteObjResponse) Reset() {
	*x = DeleteObjResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoplite_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteObjResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjResponse) ProtoMessage() {}

func (x *DeleteObjResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoplite_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjResponse) Descriptor() ([]byte, []int) {
	return file_hoplite_proto_rawDescGZIP(), []int{14}
}

var File_hoplite_proto protoreflect.FileDescriptor

var file_hoplite_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x22, 0xd9, 0x01, 0x0a, 0x0b, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x47, 0x0a, 0x0d,
	0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x6f, 0x62, 0x6a, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x54,
	0x6f, 0x4f, 0x62, 0x6a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x49, 0x64,
	0x54, 0x6f, 0x4f, 0x62, 0x6a, 0x1a, 0x3d, 0x0a, 0x0f, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x54, 0x6f,
	0x4f, 0x62, 0x6a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x0e, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x0e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x22, 0x23, 0x0a,
	0x0f, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72,
	0x65, 0x73, 0x22, 0xab, 0x01, 0x0a, 0x07, 0x4f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x4a, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x68, 0x6f, 0x70,
	0x6c, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x1a, 0x40,
	0x0a, 0x12, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x21, 0x0a, 0x0d, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x55, 0x0a, 0x0e, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x4f,
	0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x77, 0x61, 0x73, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x77, 0x61, 0x73, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x60, 0x0a, 0x0d, 0x4f, 0x64,
	0x73, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68,
	0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x74, 0x6c, 0x5f, 0x6d, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x74, 0x6c, 0x4d, 0x73, 0x22, 0x10, 0x0a, 0x0e,
	0x4f, 0x64, 0x73, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x41,
	0x0a, 0x10, 0x4f, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x13, 0x0a, 0x11, 0x4f, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x48, 0x0a, 0x13, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x22, 0x2e, 0x0a, 0x14, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4f, 0x62, 0x6a,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x22, 0x2f, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd2, 0x03, 0x0a, 0x07, 0x48, 0x6f, 0x70, 0x6c, 0x69,
	0x74, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x68,
	0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x4f,
	0x64, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a,
	0x06, 0x4f, 0x64, 0x73, 0x53, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74,
	0x65, 0x2e, 0x4f, 0x64, 0x73, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x64, 0x73, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x4f, 0x64, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e,
	0x4f, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x64, 0x73, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x1c, 0x2e, 0x68,
	0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x68, 0x6f, 0x70,
	0x6c, 0x69, 0x74, 0x65, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4f, 0x62,
	0x6a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x12, 0x19, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x0c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x14, 0x2e,
	0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x6e, 0x73, 0x12, 0x17, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69,
	0x74, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x41, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3c, 0x5a, 0x3a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x6c, 0x69, 0x61, 0x6e,
	0x4c, 0x65, 0x65, 0x31, 0x32, 0x33, 0x2f, 0x68, 0x6f, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x2d, 0x67,
	0x6f, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x68, 0x6f, 0x70, 0x6c,
	0x69, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_hoplite_proto_rawDescOnce sync.Once
	file_hoplite_proto_rawDescData = file_hoplite_proto_rawDesc
)

func file_hoplite_proto_rawDescGZIP() []byte {
	file_hoplite_proto_rawDescOnce.Do(func() {
		file_hoplite_proto_rawDescData = protoimpl.X.CompressGZIP(file_hoplite_proto_rawDescData)
	})
	return file_hoplite_proto_rawDescData
}

var file_hoplite_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_hoplite_proto_goTypes = []interface{}{
	(*TaskRequest)(nil),          // 0: hoplite.TaskRequest
	(*TaskResponse)(nil),         // 1: hoplite.TaskResponse
	(*TaskAnsRequest)(nil),       // 2: hoplite.TaskAnsRequest
	(*TaskAnsResponse)(nil),      // 3: hoplite.TaskAnsResponse
	(*OdsInfo)(nil),              // 4: hoplite.OdsInfo
	(*OdsGetRequest)(nil),        // 5: hoplite.OdsGetRequest
	(*OdsGetResponse)(nil),       // 6: hoplite.OdsGetResponse
	(*OdsSetRequest)(nil),        // 7: hoplite.OdsSetRequest
	(*OdsSetResponse)(nil),       // 8: hoplite.OdsSetResponse
	(*OdsDeleteRequest)(nil),     // 9: hoplite.OdsDeleteRequest
	(*OdsDeleteResponse)(nil),    // 10: hoplite.OdsDeleteResponse
	(*BroadcastObjRequest)(nil),  // 11: hoplite.BroadcastObjRequest
	(*BroadcastObjResponse)(nil), // 12: hoplite.BroadcastObjResponse
	(*DeleteObjRequest)(nil),     // 13: hoplite.DeleteObjRequest
	(*DeleteObjResponse)(nil),    // 14: hoplite.DeleteObjResponse
	nil,                          // 15: hoplite.TaskRequest.ObjIdToObjEntry
	nil,                          // 16: hoplite.OdsInfo.LocationInfosEntry
}
var file_hoplite_proto_depIdxs = []int32{
	15, // 0: hoplite.TaskRequest.obj_id_to_obj:type_name -> hoplite.TaskRequest.ObjIdToObjEntry
	16, // 1: hoplite.OdsInfo.location_infos:type_name -> hoplite.OdsInfo.LocationInfosEntry
	4,  // 2: hoplite.OdsGetResponse.value:type_name -> hoplite.OdsInfo
	4,  // 3: hoplite.OdsSetRequest.value:type_name -> hoplite.OdsInfo
	5,  // 4: hoplite.Hoplite.OdsGet:input_type -> hoplite.OdsGetRequest
	7,  // 5: hoplite.Hoplite.OdsSet:input_type -> hoplite.OdsSetRequest
	9,  // 6: hoplite.Hoplite.OdsDelete:input_type -> hoplite.OdsDeleteRequest
	11, // 7: hoplite.Hoplite.BroadcastObj:input_type -> hoplite.BroadcastObjRequest
	13, // 8: hoplite.Hoplite.DeleteObj:input_type -> hoplite.DeleteObjRequest
	0,  // 9: hoplite.Hoplite.ScheduleTask:input_type -> hoplite.TaskRequest
	2,  // 10: hoplite.Hoplite.GetTaskAns:input_type -> hoplite.TaskAnsRequest
	6,  // 11: hoplite.Hoplite.OdsGet:output_type -> hoplite.OdsGetResponse
	8,  // 12: hoplite.Hoplite.OdsSet:output_type -> hoplite.OdsSetResponse
	10, // 13: hoplite.Hoplite.OdsDelete:output_type -> hoplite.OdsDeleteResponse
	12, // 14: hoplite.Hoplite.BroadcastObj:output_type -> hoplite.BroadcastObjResponse
	14, // 15: hoplite.Hoplite.DeleteObj:output_type -> hoplite.DeleteObjResponse
	1,  // 16: hoplite.Hoplite.ScheduleTask:output_type -> hoplite.TaskResponse
	3,  // 17: hoplite.Hoplite.GetTaskAns:output_type -> hoplite.TaskAnsResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hoplite_proto_init() }
func file_hoplite_proto_init() {
	if File_hoplite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hoplite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskAnsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskAnsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OdsDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastObjRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastObjResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteObjRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoplite_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteObjResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hoplite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hoplite_proto_goTypes,
		DependencyIndexes: file_hoplite_proto_depIdxs,
		MessageInfos:      file_hoplite_proto_msgTypes,
	}.Build()
	File_hoplite_proto = out.File
	file_hoplite_proto_rawDesc = nil
	file_hoplite_proto_goTypes = nil
	file_hoplite_proto_depIdxs = nil
}
