// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: hoplite.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HopliteClient is the client API for Hoplite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HopliteClient interface {
	// RPC calls between nodes for Ods
	OdsGet(ctx context.Context, in *OdsGetRequest, opts ...grpc.CallOption) (*OdsGetResponse, error)
	OdsSet(ctx context.Context, in *OdsSetRequest, opts ...grpc.CallOption) (*OdsSetResponse, error)
	OdsDelete(ctx context.Context, in *OdsDeleteRequest, opts ...grpc.CallOption) (*OdsDeleteResponse, error)
	// RPC calls between nodes for Ods
	BroadcastObj(ctx context.Context, in *BroadcastObjRequest, opts ...grpc.CallOption) (*BroadcastObjResponse, error)
	DeleteObj(ctx context.Context, in *DeleteObjRequest, opts ...grpc.CallOption) (*DeleteObjResponse, error)
	// RPC call between TaskScheduler and nodes
	ScheduleTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetTaskAns(ctx context.Context, in *TaskAnsRequest, opts ...grpc.CallOption) (*TaskAnsResponse, error)
}

type hopliteClient struct {
	cc grpc.ClientConnInterface
}

func NewHopliteClient(cc grpc.ClientConnInterface) HopliteClient {
	return &hopliteClient{cc}
}

func (c *hopliteClient) OdsGet(ctx context.Context, in *OdsGetRequest, opts ...grpc.CallOption) (*OdsGetResponse, error) {
	out := new(OdsGetResponse)
	err := c.cc.Invoke(ctx, "/hoplite.Hoplite/OdsGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopliteClient) OdsSet(ctx context.Context, in *OdsSetRequest, opts ...grpc.CallOption) (*OdsSetResponse, error) {
	out := new(OdsSetResponse)
	err := c.cc.Invoke(ctx, "/hoplite.Hoplite/OdsSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopliteClient) OdsDelete(ctx context.Context, in *OdsDeleteRequest, opts ...grpc.CallOption) (*OdsDeleteResponse, error) {
	out := new(OdsDeleteResponse)
	err := c.cc.Invoke(ctx, "/hoplite.Hoplite/OdsDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopliteClient) BroadcastObj(ctx context.Context, in *BroadcastObjRequest, opts ...grpc.CallOption) (*BroadcastObjResponse, error) {
	out := new(BroadcastObjResponse)
	err := c.cc.Invoke(ctx, "/hoplite.Hoplite/BroadcastObj", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopliteClient) DeleteObj(ctx context.Context, in *DeleteObjRequest, opts ...grpc.CallOption) (*DeleteObjResponse, error) {
	out := new(DeleteObjResponse)
	err := c.cc.Invoke(ctx, "/hoplite.Hoplite/DeleteObj", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopliteClient) ScheduleTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/hoplite.Hoplite/ScheduleTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopliteClient) GetTaskAns(ctx context.Context, in *TaskAnsRequest, opts ...grpc.CallOption) (*TaskAnsResponse, error) {
	out := new(TaskAnsResponse)
	err := c.cc.Invoke(ctx, "/hoplite.Hoplite/GetTaskAns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HopliteServer is the server API for Hoplite service.
// All implementations must embed UnimplementedHopliteServer
// for forward compatibility
type HopliteServer interface {
	// RPC calls between nodes for Ods
	OdsGet(context.Context, *OdsGetRequest) (*OdsGetResponse, error)
	OdsSet(context.Context, *OdsSetRequest) (*OdsSetResponse, error)
	OdsDelete(context.Context, *OdsDeleteRequest) (*OdsDeleteResponse, error)
	// RPC calls between nodes for Ods
	BroadcastObj(context.Context, *BroadcastObjRequest) (*BroadcastObjResponse, error)
	DeleteObj(context.Context, *DeleteObjRequest) (*DeleteObjResponse, error)
	// RPC call between TaskScheduler and nodes
	ScheduleTask(context.Context, *TaskRequest) (*TaskResponse, error)
	GetTaskAns(context.Context, *TaskAnsRequest) (*TaskAnsResponse, error)
	mustEmbedUnimplementedHopliteServer()
}

// UnimplementedHopliteServer must be embedded to have forward compatible implementations.
type UnimplementedHopliteServer struct {
}

func (UnimplementedHopliteServer) OdsGet(context.Context, *OdsGetRequest) (*OdsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OdsGet not implemented")
}
func (UnimplementedHopliteServer) OdsSet(context.Context, *OdsSetRequest) (*OdsSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OdsSet not implemented")
}
func (UnimplementedHopliteServer) OdsDelete(context.Context, *OdsDeleteRequest) (*OdsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OdsDelete not implemented")
}
func (UnimplementedHopliteServer) BroadcastObj(context.Context, *BroadcastObjRequest) (*BroadcastObjResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastObj not implemented")
}
func (UnimplementedHopliteServer) DeleteObj(context.Context, *DeleteObjRequest) (*DeleteObjResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObj not implemented")
}
func (UnimplementedHopliteServer) ScheduleTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleTask not implemented")
}
func (UnimplementedHopliteServer) GetTaskAns(context.Context, *TaskAnsRequest) (*TaskAnsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskAns not implemented")
}
func (UnimplementedHopliteServer) mustEmbedUnimplementedHopliteServer() {}

// UnsafeHopliteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HopliteServer will
// result in compilation errors.
type UnsafeHopliteServer interface {
	mustEmbedUnimplementedHopliteServer()
}

func RegisterHopliteServer(s grpc.ServiceRegistrar, srv HopliteServer) {
	s.RegisterService(&Hoplite_ServiceDesc, srv)
}

func _Hoplite_OdsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OdsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopliteServer).OdsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hoplite.Hoplite/OdsGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopliteServer).OdsGet(ctx, req.(*OdsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hoplite_OdsSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OdsSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopliteServer).OdsSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hoplite.Hoplite/OdsSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopliteServer).OdsSet(ctx, req.(*OdsSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hoplite_OdsDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OdsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopliteServer).OdsDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hoplite.Hoplite/OdsDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopliteServer).OdsDelete(ctx, req.(*OdsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hoplite_BroadcastObj_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastObjRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopliteServer).BroadcastObj(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hoplite.Hoplite/BroadcastObj",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopliteServer).BroadcastObj(ctx, req.(*BroadcastObjRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hoplite_DeleteObj_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopliteServer).DeleteObj(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hoplite.Hoplite/DeleteObj",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopliteServer).DeleteObj(ctx, req.(*DeleteObjRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hoplite_ScheduleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopliteServer).ScheduleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hoplite.Hoplite/ScheduleTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopliteServer).ScheduleTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hoplite_GetTaskAns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskAnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopliteServer).GetTaskAns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hoplite.Hoplite/GetTaskAns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopliteServer).GetTaskAns(ctx, req.(*TaskAnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hoplite_ServiceDesc is the grpc.ServiceDesc for Hoplite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hoplite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hoplite.Hoplite",
	HandlerType: (*HopliteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OdsGet",
			Handler:    _Hoplite_OdsGet_Handler,
		},
		{
			MethodName: "OdsSet",
			Handler:    _Hoplite_OdsSet_Handler,
		},
		{
			MethodName: "OdsDelete",
			Handler:    _Hoplite_OdsDelete_Handler,
		},
		{
			MethodName: "BroadcastObj",
			Handler:    _Hoplite_BroadcastObj_Handler,
		},
		{
			MethodName: "DeleteObj",
			Handler:    _Hoplite_DeleteObj_Handler,
		},
		{
			MethodName: "ScheduleTask",
			Handler:    _Hoplite_ScheduleTask_Handler,
		},
		{
			MethodName: "GetTaskAns",
			Handler:    _Hoplite_GetTaskAns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hoplite.proto",
}
